"""baseline

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-06-18 00:51:11.813157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('parent_niche_id', sa.UUID(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('hashtags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('content_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('platforms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('source_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_niches_slug'), 'niches', ['slug'], unique=True)
    op.create_table('provider_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('primary_provider', sa.String(length=50), nullable=False),
    sa.Column('primary_model', sa.String(length=100), nullable=False),
    sa.Column('fallback_provider_1', sa.String(length=50), nullable=True),
    sa.Column('fallback_model_1', sa.String(length=100), nullable=True),
    sa.Column('fallback_provider_2', sa.String(length=50), nullable=True),
    sa.Column('fallback_model_2', sa.String(length=100), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('cost_per_1k_input', sa.Float(), nullable=False),
    sa.Column('cost_per_1k_output', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_type', name='uq_provider_policy_task')
    )
    op.create_index(op.f('ix_provider_policies_task_type'), 'provider_policies', ['task_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('google_id', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mfa_backup_codes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('prompt_catalog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('niche_id', sa.UUID(), nullable=True),
    sa.Column('active_version_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_catalog_name'), 'prompt_catalog', ['name'], unique=True)
    op.create_table('source_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('niche_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.Enum('RSS', 'YOUTUBE_CHANNEL', 'SUBREDDIT', 'TWITTER_LIST', 'API', 'GITHUB_TRENDING', 'PRODUCT_HUNT', 'ARXIV', 'WEB_SCRAPE', name='sourcetype', native_enum=False), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('feed_url', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('scrape_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('fetch_frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('articles_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_registry_niche_id'), 'source_registry', ['niche_id'], unique=False)
    op.create_table('trends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('niche_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('trend_type', sa.Enum('HASHTAG', 'SOUND', 'FORMAT', 'TOPIC', 'CHALLENGE', 'MEME', name='trendtype', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hashtags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('example_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('trend_velocity', sa.Float(), nullable=False),
    sa.Column('peak_predicted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('peaked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RISING', 'PEAK', 'DECLINING', 'DEAD', 'EVERGREEN', name='trendstatus', native_enum=False), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trends_niche_id'), 'trends', ['niche_id'], unique=False)
    op.create_index('ix_trends_niche_score', 'trends', ['niche_id', 'trend_score'], unique=False, postgresql_where="status IN ('rising', 'peak')")
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('plan_tier', sa.Enum('FREE', 'PRO', 'BUSINESS', 'ENTERPRISE', name='plantier', native_enum=False), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('onboarding_step', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=200), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=False),
    sa.Column('subscription_status', sa.String(length=20), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index(op.f('ix_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False)
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('agent_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('run_frequency', sa.String(length=20), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'agent_type', name='uq_agent_config')
    )
    op.create_index(op.f('ix_agent_configs_workspace_id'), 'agent_configs', ['workspace_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.String(length=100), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'LEASED', 'RUNNING', 'AWAITING_APPROVAL', 'SUCCESS', 'PARTIAL', 'RETRYABLE_FAILED', 'FAILED', 'CANCELLED', 'DEAD_LETTER', name='agentrunstatus', native_enum=False), nullable=False),
    sa.Column('scout_duration_s', sa.Float(), nullable=True),
    sa.Column('analyst_duration_s', sa.Float(), nullable=True),
    sa.Column('checker_duration_s', sa.Float(), nullable=True),
    sa.Column('creative_duration_s', sa.Float(), nullable=True),
    sa.Column('items_fetched', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('items_scored', sa.Integer(), nullable=False),
    sa.Column('items_fact_checked', sa.Integer(), nullable=False),
    sa.Column('items_generated', sa.Integer(), nullable=False),
    sa.Column('gap_signals_found', sa.Integer(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('stage_errors', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('failure_class', sa.String(length=100), nullable=True),
    sa.Column('input_ref', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('output_ref', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_correlation_id'), 'agent_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_workspace_id'), 'agent_runs', ['workspace_id'], unique=False)
    op.create_index('ix_agent_runs_workspace_status', 'agent_runs', ['workspace_id', 'status', 'started_at'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('policy_key', sa.String(length=100), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('decided_by', sa.String(length=100), nullable=True),
    sa.Column('decision', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='approvaldecision', native_enum=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_workspace_id'), 'approval_requests', ['workspace_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('before_summary', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('after_summary', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_index('ix_audit_workspace_actor', 'audit_logs', ['workspace_id', 'actor_id', 'created_at'], unique=False)
    op.create_table('budget_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('monthly_llm_budget_usd', sa.Float(), nullable=False),
    sa.Column('monthly_media_budget_usd', sa.Float(), nullable=False),
    sa.Column('max_cost_per_run_usd', sa.Float(), nullable=False),
    sa.Column('max_publish_per_day', sa.Integer(), nullable=False),
    sa.Column('max_agent_runs_per_day', sa.Integer(), nullable=False),
    sa.Column('approval_required_above_usd', sa.Float(), nullable=False),
    sa.Column('auto_downgrade_threshold_pct', sa.Integer(), nullable=False),
    sa.Column('hard_stop_on_budget', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_policies_workspace_id'), 'budget_policies', ['workspace_id'], unique=False)
    op.create_table('competitor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('platform_username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('niche_id', sa.UUID(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('avg_engagement_rate', sa.Float(), nullable=False),
    sa.Column('posting_frequency', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tracking_since', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_tracked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'platform', 'platform_username', name='uq_competitor_profile')
    )
    op.create_index(op.f('ix_competitor_profiles_workspace_id'), 'competitor_profiles', ['workspace_id'], unique=False)
    op.create_table('creator_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal_type', sa.Enum('CONTENT_COUNT', 'FOLLOWERS', 'VIEWS', 'ENGAGEMENT', 'REVENUE', 'CUSTOM', name='goaltype', native_enum=False), nullable=False),
    sa.Column('period', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', name='goalperiod', native_enum=False), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'FAILED', 'ARCHIVED', name='goalstatus', native_enum=False), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_schedule', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('streak_count', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_goals_workspace_id'), 'creator_goals', ['workspace_id'], unique=False)
    op.create_table('device_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'token', name='uq_device_token')
    )
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_device_tokens_workspace_id'), 'device_tokens', ['workspace_id'], unique=False)
    op.create_table('media_edits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('original_s3_key', sa.String(length=500), nullable=False),
    sa.Column('edited_s3_key', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_s3_key', sa.String(length=500), nullable=True),
    sa.Column('transcript_s3_key', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'DOWNLOADING', 'TRANSCRIBING', 'ANALYZING', 'RENDERING', 'UPLOADING', 'COMPLETED', 'FAILED', 'CANCELLED', name='mediaeditstatus', native_enum=False), nullable=False),
    sa.Column('target_platform', sa.String(length=30), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('edit_recipe', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('ai_hook_analysis', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_captions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('original_duration_seconds', sa.Float(), nullable=True),
    sa.Column('edited_duration_seconds', sa.Float(), nullable=True),
    sa.Column('original_size_bytes', sa.Integer(), nullable=True),
    sa.Column('edited_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=100), nullable=True),
    sa.Column('last_lease_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_edits_status'), 'media_edits', ['status'], unique=False)
    op.create_index(op.f('ix_media_edits_workspace_id'), 'media_edits', ['workspace_id'], unique=False)
    op.create_index('ix_media_edits_workspace_status', 'media_edits', ['workspace_id', 'status', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_push_sent', sa.Boolean(), nullable=False),
    sa.Column('is_email_sent', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'scheduled_for'], unique=False, postgresql_where='is_read = false')
    op.create_index(op.f('ix_notifications_workspace_id'), 'notifications', ['workspace_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DISPATCHED', 'FAILED', 'DEAD_LETTER', name='outboxstatus', native_enum=False), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_workspace_id'), 'outbox_events', ['workspace_id'], unique=False)
    op.create_index('ix_outbox_pending', 'outbox_events', ['status', 'next_attempt_at'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt_template', sa.Text(), nullable=True),
    sa.Column('examples', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_provider', sa.String(length=50), nullable=True),
    sa.Column('recommended_model', sa.String(length=100), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rollout_pct', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['prompt_catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_id', 'version', name='uq_prompt_version')
    )
    op.create_index(op.f('ix_prompt_versions_catalog_id'), 'prompt_versions', ['catalog_id'], unique=False)
    op.create_table('social_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('platform_user_id', sa.String(length=200), nullable=False),
    sa.Column('platform_username', sa.String(length=100), nullable=True),
    sa.Column('platform_display_name', sa.String(length=200), nullable=True),
    sa.Column('platform_avatar_url', sa.Text(), nullable=True),
    sa.Column('platform_url', sa.Text(), nullable=True),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_scope', sa.Text(), nullable=True),
    sa.Column('token_status', sa.Enum('VALID', 'EXPIRED', 'REVOKED', 'REFRESH_FAILED', name='tokenstatus', native_enum=False), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('rate_limit_state', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'platform', 'platform_user_id', name='uq_social_account')
    )
    op.create_index('ix_social_accounts_workspace_active', 'social_accounts', ['workspace_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_social_accounts_workspace_id'), 'social_accounts', ['workspace_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_registry_id', sa.UUID(), nullable=True),
    sa.Column('source_key', sa.String(length=100), nullable=False),
    sa.Column('source_label', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_points', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.Enum('MODEL_RELEASE', 'RESEARCH_PAPER', 'PRODUCT_LAUNCH', 'FUNDING', 'OPINION_TAKE', 'TUTORIAL', 'INDUSTRY_NEWS', 'OPEN_SOURCE', 'POLICY_SAFETY', 'TREND', 'VIRAL_CONTENT', 'NEWS', 'OTHER', name='contentcategory', native_enum=False), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('is_trending', sa.Boolean(), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=True),
    sa.Column('niche_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_registry_id'], ['source_registry.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index('ix_source_docs_relevance', 'source_documents', ['relevance_score', 'fetched_at'], unique=False)
    op.create_index(op.f('ix_source_documents_category'), 'source_documents', ['category'], unique=False)
    op.create_index(op.f('ix_source_documents_dedup_hash'), 'source_documents', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_source_documents_fetched_at'), 'source_documents', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_source_documents_is_processed'), 'source_documents', ['is_processed'], unique=False)
    op.create_index(op.f('ix_source_documents_source_key'), 'source_documents', ['source_key'], unique=False)
    op.create_index(op.f('ix_source_documents_source_registry_id'), 'source_documents', ['source_registry_id'], unique=False)
    op.create_table('usage_meters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('meter_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('billable_quantity', sa.Float(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('source_run_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_meters_workspace_id'), 'usage_meters', ['workspace_id'], unique=False)
    op.create_index('ix_usage_workspace_type', 'usage_meters', ['workspace_id', 'meter_type', 'recorded_at'], unique=False)
    op.create_table('webhook_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('external_event_id', sa.String(length=200), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_status', sa.Enum('RECEIVED', 'VALIDATED', 'DUPLICATE', 'PROCESSED', 'RETRYABLE_FAILED', 'FAILED', name='webhookprocessingstatus', native_enum=False), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('linked_resource_type', sa.String(length=100), nullable=True),
    sa.Column('linked_resource_id', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_provider_event', 'webhook_receipts', ['provider', 'external_event_id'], unique=False)
    op.create_index('ix_webhook_provider_hash', 'webhook_receipts', ['provider', 'payload_hash'], unique=False)
    op.create_index(op.f('ix_webhook_receipts_workspace_id'), 'webhook_receipts', ['workspace_id'], unique=False)
    op.create_table('workspace_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'EDITOR', 'ANALYST', 'VIEWER', name='workspacerole', native_enum=False), nullable=False),
    sa.Column('invite_status', sa.Enum('INVITED', 'ACTIVE', 'SUSPENDED', 'REMOVED', name='invitestatus', native_enum=False), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_user')
    )
    op.create_index(op.f('ix_workspace_memberships_user_id'), 'workspace_memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_memberships_workspace_id'), 'workspace_memberships', ['workspace_id'], unique=False)
    op.create_table('workspace_niches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('niche_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('content_pillars', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('target_audience', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'niche_id', name='uq_workspace_niche')
    )
    op.create_index(op.f('ix_workspace_niches_niche_id'), 'workspace_niches', ['niche_id'], unique=False)
    op.create_index(op.f('ix_workspace_niches_workspace_id'), 'workspace_niches', ['workspace_id'], unique=False)
    op.create_table('agent_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('agent_config_id', sa.UUID(), nullable=True),
    sa.Column('insight_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('action_url', sa.Text(), nullable=True),
    sa.Column('action_label', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('is_actioned', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_config_id'], ['agent_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_insights_unread', 'agent_insights', ['workspace_id', 'priority'], unique=False, postgresql_where='is_read = false AND is_dismissed = false')
    op.create_index(op.f('ix_agent_insights_workspace_id'), 'agent_insights', ['workspace_id'], unique=False)
    op.create_table('agent_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_steps_agent_run_id'), 'agent_steps', ['agent_run_id'], unique=False)
    op.create_table('competitor_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('observation_type', sa.String(length=30), nullable=False),
    sa.Column('platform_post_id', sa.String(length=200), nullable=True),
    sa.Column('content_type', sa.String(length=30), nullable=True),
    sa.Column('content_summary', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('engagement_metrics', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('viral_score', sa.Float(), nullable=False),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('content_gaps', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_observations_competitor_id'), 'competitor_observations', ['competitor_id'], unique=False)
    op.create_table('dm_inbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('social_account_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('platform_message_id', sa.String(length=200), nullable=True),
    sa.Column('sender_platform_id', sa.String(length=200), nullable=False),
    sa.Column('sender_username', sa.String(length=100), nullable=False),
    sa.Column('sender_display_name', sa.String(length=200), nullable=True),
    sa.Column('sender_avatar_url', sa.Text(), nullable=True),
    sa.Column('sender_followers_count', sa.Integer(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('message_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_business_inquiry', sa.Boolean(), nullable=False),
    sa.Column('ai_category', sa.Enum('BRAND_DEAL', 'COLLAB', 'FAN', 'SPAM', 'HATE', 'QUESTION', 'SUPPORT', 'UNKNOWN', name='dmcategory', native_enum=False), nullable=True),
    sa.Column('ai_priority', sa.Integer(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_sentiment', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('ai_suggested_reply', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_replied', sa.Boolean(), nullable=False),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collaboration_id', sa.UUID(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], name='fk_dm_inbox_collaboration_id', use_alter=True),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dm_inbox_social_account_id'), 'dm_inbox', ['social_account_id'], unique=False)
    op.create_index(op.f('ix_dm_inbox_workspace_id'), 'dm_inbox', ['workspace_id'], unique=False)
    op.create_index('ix_dm_platform_message', 'dm_inbox', ['platform', 'platform_message_id'], unique=False)
    op.create_index('ix_dm_workspace_unread', 'dm_inbox', ['workspace_id', 'is_read', 'ai_priority'], unique=False)
    op.create_table('goal_check_ins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('value_at_checkin', sa.Float(), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('agent_analysis', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['creator_goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_check_ins_goal_id'), 'goal_check_ins', ['goal_id'], unique=False)
    op.create_table('source_document_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('virality_score', sa.Float(), nullable=False),
    sa.Column('cross_source_count', sa.Integer(), nullable=False),
    sa.Column('trend_velocity', sa.Float(), nullable=False),
    sa.Column('sentiment_breakdown', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_value_gap', sa.Boolean(), nullable=False),
    sa.Column('gap_explanation', sa.Text(), nullable=True),
    sa.Column('suggested_angle', sa.Text(), nullable=True),
    sa.Column('broll_assets', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('fact_check_passed', sa.Boolean(), nullable=True),
    sa.Column('fact_check_confidence', sa.Float(), nullable=True),
    sa.Column('flagged_claims', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_document_insights_source_document_id'), 'source_document_insights', ['source_document_id'], unique=True)
    op.create_table('workspace_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('agent_run_id', sa.UUID(), nullable=True),
    sa.Column('insight_type', sa.Enum('TREND_ALERT', 'COMPETITOR_MOVE', 'CONTENT_IDEA', 'GOAL_WARNING', 'COLLABORATION_OPPORTUNITY', 'GROWTH_HACK', 'POSTING_REMINDER', 'ALGORITHM_CHANGE', 'NEWS_OPPORTUNITY', 'PERFORMANCE_INSIGHT', name='insighttype', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('action_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('niche_relevance_score', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('is_actioned', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workspace_insights_unread', 'workspace_insights', ['workspace_id', 'priority'], unique=False, postgresql_where='is_read = false')
    op.create_index(op.f('ix_workspace_insights_workspace_id'), 'workspace_insights', ['workspace_id'], unique=False)
    op.create_table('collaborations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('collab_type', sa.Enum('BRAND_DEAL', 'SPONSORSHIP', 'AFFILIATE', 'UGC', 'COLLAB', 'PR', 'OTHER', name='collaborationtype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('INQUIRY', 'NEGOTIATING', 'CONTRACT_SENT', 'CONTRACT_SIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'REJECTED', name='collaborationstatus', native_enum=False), nullable=False),
    sa.Column('brand_name', sa.String(length=200), nullable=False),
    sa.Column('brand_email', sa.String(length=255), nullable=True),
    sa.Column('brand_website', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_platform', sa.String(length=30), nullable=True),
    sa.Column('contact_handle', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deliverables', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('offered_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('negotiated_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_type', sa.Enum('FLAT_FEE', 'CPM', 'REVENUE_SHARE', 'BARTER', 'HYBRID', name='paymenttype', native_enum=False), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'INVOICED', 'PAID', 'OVERDUE', 'CANCELLED', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('ai_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('ai_red_flags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('source_platform', sa.String(length=30), nullable=True),
    sa.Column('source_dm_id', sa.UUID(), nullable=True),
    sa.Column('deal_starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deal_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_dm_id'], ['dm_inbox.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collab_workspace_status', 'collaborations', ['workspace_id', 'status'], unique=False)
    op.create_index(op.f('ix_collaborations_workspace_id'), 'collaborations', ['workspace_id'], unique=False)
    op.create_table('content_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('IDEA', 'DRAFT', 'REVIEW', 'APPROVED', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED', 'FAILED', name='projectstatus', native_enum=False), nullable=False),
    sa.Column('niche_id', sa.UUID(), nullable=True),
    sa.Column('content_pillars', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('source_insight_id', sa.UUID(), nullable=True),
    sa.Column('source_trend_id', sa.UUID(), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('hooks', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('target_platforms', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('virality_score', sa.Float(), nullable=True),
    sa.Column('ai_rationale', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.ForeignKeyConstraint(['source_insight_id'], ['workspace_insights.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_trend_id'], ['trends.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_projects_status'), 'content_projects', ['status'], unique=False)
    op.create_index(op.f('ix_content_projects_workspace_id'), 'content_projects', ['workspace_id'], unique=False)
    op.create_index('ix_content_projects_workspace_status', 'content_projects', ['workspace_id', 'status', 'created_at'], unique=False)
    op.create_table('content_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('media_kind', sa.String(length=30), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('source_lineage', sa.String(length=50), nullable=True),
    sa.Column('retention_class', sa.String(length=30), nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['content_projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_assets_workspace_id'), 'content_assets', ['workspace_id'], unique=False)
    op.create_table('content_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('target_platform', sa.String(length=30), nullable=False),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('hashtags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('call_to_action', sa.Text(), nullable=True),
    sa.Column('script_outline', sa.Text(), nullable=True),
    sa.Column('thread_tweets', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('engagement_tips', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('authoring_source', sa.Enum('HUMAN', 'ASSISTANT', 'HYBRID', name='authoringsource', native_enum=False), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('provider_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('approval_state', sa.Enum('NOT_REQUIRED', 'PENDING', 'APPROVED', 'REJECTED', name='approvalstate', native_enum=False), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=False),
    sa.Column('total_likes', sa.Integer(), nullable=False),
    sa.Column('total_comments', sa.Integer(), nullable=False),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.Column('total_saves', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['content_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_variants_project_id'), 'content_variants', ['project_id'], unique=False)
    op.create_index(op.f('ix_content_variants_workspace_id'), 'content_variants', ['workspace_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collaboration_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('contract_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'VIEWED', 'SIGNED', 'COUNTERSIGNED', 'EXPIRED', 'VOIDED', name='contractstatus', native_enum=False), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature_provider', sa.String(length=30), nullable=True),
    sa.Column('external_contract_id', sa.String(length=200), nullable=True),
    sa.Column('ai_review_summary', sa.Text(), nullable=True),
    sa.Column('ai_red_flags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_contract_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contract_collab_status', 'contracts', ['collaboration_id', 'status'], unique=False)
    op.create_index(op.f('ix_contracts_collaboration_id'), 'contracts', ['collaboration_id'], unique=False)
    op.create_index(op.f('ix_contracts_workspace_id'), 'contracts', ['workspace_id'], unique=False)
    op.create_table('analytics_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('content_variant_id', sa.UUID(), nullable=True),
    sa.Column('social_account_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('profile_visits', sa.Integer(), nullable=False),
    sa.Column('link_clicks', sa.Integer(), nullable=False),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('avg_watch_time_seconds', sa.Integer(), nullable=True),
    sa.Column('estimated_revenue_usd', sa.Float(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('sentiment_breakdown', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('top_comments', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_variant_id'], ['content_variants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_facts_content_variant_id'), 'analytics_facts', ['content_variant_id'], unique=False)
    op.create_index(op.f('ix_analytics_facts_recorded_at'), 'analytics_facts', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_analytics_facts_workspace_id'), 'analytics_facts', ['workspace_id'], unique=False)
    op.create_index('ix_analytics_workspace_recorded', 'analytics_facts', ['workspace_id', 'platform', 'recorded_at'], unique=False)
    op.create_table('publish_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('content_variant_id', sa.UUID(), nullable=False),
    sa.Column('social_account_id', sa.UUID(), nullable=False),
    sa.Column('target_platform', sa.String(length=30), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'LEASED', 'RUNNING', 'AWAITING_APPROVAL', 'COMPLETED', 'RETRYABLE_FAILED', 'FAILED', 'CANCELLED', 'DEAD_LETTER', name='publishstatus', native_enum=False), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('lease_owner', sa.String(length=100), nullable=True),
    sa.Column('last_lease_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('platform_post_id', sa.String(length=200), nullable=True),
    sa.Column('platform_post_url', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_variant_id'], ['content_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_publish_jobs_schedule', 'publish_jobs', ['workspace_id', 'scheduled_at', 'status'], unique=False)
    op.create_index(op.f('ix_publish_jobs_workspace_id'), 'publish_jobs', ['workspace_id'], unique=False)
    op.create_table('publish_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('publish_job_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('provider_response_code', sa.Integer(), nullable=True),
    sa.Column('provider_request_id', sa.String(length=200), nullable=True),
    sa.Column('provider_response', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('failure_class', sa.String(length=100), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('payload_snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['publish_job_id'], ['publish_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_attempts_publish_job_id'), 'publish_attempts', ['publish_job_id'], unique=False)
    # Deferred circular FK: dm_inbox.collaboration_id -> collaborations.id
    op.create_foreign_key(
        'fk_dm_inbox_collaboration_id',
        'dm_inbox', 'collaborations',
        ['collaboration_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_dm_inbox_collaboration_id', 'dm_inbox', type_='foreignkey')
    op.drop_index(op.f('ix_publish_attempts_publish_job_id'), table_name='publish_attempts')
    op.drop_table('publish_attempts')
    op.drop_index(op.f('ix_publish_jobs_workspace_id'), table_name='publish_jobs')
    op.drop_index('ix_publish_jobs_schedule', table_name='publish_jobs')
    op.drop_table('publish_jobs')
    op.drop_index('ix_analytics_workspace_recorded', table_name='analytics_facts')
    op.drop_index(op.f('ix_analytics_facts_workspace_id'), table_name='analytics_facts')
    op.drop_index(op.f('ix_analytics_facts_recorded_at'), table_name='analytics_facts')
    op.drop_index(op.f('ix_analytics_facts_content_variant_id'), table_name='analytics_facts')
    op.drop_table('analytics_facts')
    op.drop_index(op.f('ix_contracts_workspace_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_collaboration_id'), table_name='contracts')
    op.drop_index('ix_contract_collab_status', table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_content_variants_workspace_id'), table_name='content_variants')
    op.drop_index(op.f('ix_content_variants_project_id'), table_name='content_variants')
    op.drop_table('content_variants')
    op.drop_index(op.f('ix_content_assets_workspace_id'), table_name='content_assets')
    op.drop_table('content_assets')
    op.drop_index('ix_content_projects_workspace_status', table_name='content_projects')
    op.drop_index(op.f('ix_content_projects_workspace_id'), table_name='content_projects')
    op.drop_index(op.f('ix_content_projects_status'), table_name='content_projects')
    op.drop_table('content_projects')
    op.drop_index(op.f('ix_collaborations_workspace_id'), table_name='collaborations')
    op.drop_index('ix_collab_workspace_status', table_name='collaborations')
    op.drop_table('collaborations')
    op.drop_index(op.f('ix_workspace_insights_workspace_id'), table_name='workspace_insights')
    op.drop_index('ix_workspace_insights_unread', table_name='workspace_insights', postgresql_where='is_read = false')
    op.drop_table('workspace_insights')
    op.drop_index(op.f('ix_source_document_insights_source_document_id'), table_name='source_document_insights')
    op.drop_table('source_document_insights')
    op.drop_index(op.f('ix_goal_check_ins_goal_id'), table_name='goal_check_ins')
    op.drop_table('goal_check_ins')
    op.drop_index('ix_dm_workspace_unread', table_name='dm_inbox')
    op.drop_index('ix_dm_platform_message', table_name='dm_inbox')
    op.drop_index(op.f('ix_dm_inbox_workspace_id'), table_name='dm_inbox')
    op.drop_index(op.f('ix_dm_inbox_social_account_id'), table_name='dm_inbox')
    op.drop_table('dm_inbox')
    op.drop_index(op.f('ix_competitor_observations_competitor_id'), table_name='competitor_observations')
    op.drop_table('competitor_observations')
    op.drop_index(op.f('ix_agent_steps_agent_run_id'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_agent_insights_workspace_id'), table_name='agent_insights')
    op.drop_index('ix_agent_insights_unread', table_name='agent_insights', postgresql_where='is_read = false AND is_dismissed = false')
    op.drop_table('agent_insights')
    op.drop_index(op.f('ix_workspace_niches_workspace_id'), table_name='workspace_niches')
    op.drop_index(op.f('ix_workspace_niches_niche_id'), table_name='workspace_niches')
    op.drop_table('workspace_niches')
    op.drop_index(op.f('ix_workspace_memberships_workspace_id'), table_name='workspace_memberships')
    op.drop_index(op.f('ix_workspace_memberships_user_id'), table_name='workspace_memberships')
    op.drop_table('workspace_memberships')
    op.drop_index(op.f('ix_webhook_receipts_workspace_id'), table_name='webhook_receipts')
    op.drop_index('ix_webhook_provider_hash', table_name='webhook_receipts')
    op.drop_index('ix_webhook_provider_event', table_name='webhook_receipts')
    op.drop_table('webhook_receipts')
    op.drop_index('ix_usage_workspace_type', table_name='usage_meters')
    op.drop_index(op.f('ix_usage_meters_workspace_id'), table_name='usage_meters')
    op.drop_table('usage_meters')
    op.drop_index(op.f('ix_source_documents_source_registry_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_source_key'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_is_processed'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_fetched_at'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_dedup_hash'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_category'), table_name='source_documents')
    op.drop_index('ix_source_docs_relevance', table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_social_accounts_workspace_id'), table_name='social_accounts')
    op.drop_index('ix_social_accounts_workspace_active', table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_prompt_versions_catalog_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index('ix_outbox_pending', table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_workspace_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_notifications_workspace_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_unread', table_name='notifications', postgresql_where='is_read = false')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_media_edits_workspace_status', table_name='media_edits')
    op.drop_index(op.f('ix_media_edits_workspace_id'), table_name='media_edits')
    op.drop_index(op.f('ix_media_edits_status'), table_name='media_edits')
    op.drop_table('media_edits')
    op.drop_index(op.f('ix_device_tokens_workspace_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_creator_goals_workspace_id'), table_name='creator_goals')
    op.drop_table('creator_goals')
    op.drop_index(op.f('ix_competitor_profiles_workspace_id'), table_name='competitor_profiles')
    op.drop_table('competitor_profiles')
    op.drop_index(op.f('ix_budget_policies_workspace_id'), table_name='budget_policies')
    op.drop_table('budget_policies')
    op.drop_index('ix_audit_workspace_actor', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_approval_requests_workspace_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index('ix_agent_runs_workspace_status', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_workspace_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_correlation_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_agent_configs_workspace_id'), table_name='agent_configs')
    op.drop_table('agent_configs')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_owner_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('ix_trends_niche_score', table_name='trends', postgresql_where="status IN ('rising', 'peak')")
    op.drop_index(op.f('ix_trends_niche_id'), table_name='trends')
    op.drop_table('trends')
    op.drop_index(op.f('ix_source_registry_niche_id'), table_name='source_registry')
    op.drop_table('source_registry')
    op.drop_index(op.f('ix_prompt_catalog_name'), table_name='prompt_catalog')
    op.drop_table('prompt_catalog')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_provider_policies_task_type'), table_name='provider_policies')
    op.drop_table('provider_policies')
    op.drop_index(op.f('ix_niches_slug'), table_name='niches')
    op.drop_table('niches')
    # ### end Alembic commands ###
